# travis.yml for testing radare2. Initially written in 2014-2016, by jn__.

os:
  - linux
  - osx

language: c
dist: trusty

compiler:
  - gcc
  - clang

matrix:
  exclude:
      - os: osx
        compiler: gcc

sudo: false

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - dc
      - binutils
      - cabextract
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - jq
      - gcc-4.8
      - g++-4.8

cache:
  - ccache
  - apt

before_script:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 7

script:
  - git clone --depth 1 `doc/repo REGRESSIONS`
  - ./configure --prefix=`pwd`/install > /dev/null
  - make -s -j2 > /dev/null
  - make install > /dev/null
  - export PKG_CONFIG_PATH=${TRAVIS_BUILD_DIR}/pkgcfg:${PKG_CONFIG_PATH}
  - export PATH=${TRAVIS_BUILD_DIR}/install/bin:${PATH}
  - export LD_LIBRARY_PATH=${TRAVIS_BUILD_DIR}/install/lib:${LD_LIBRARY_PATH}
  #- [ "$TRAVIS_OS_NAME" != "osx" ] && mkdir -p /tmp/kcov && pushd /tmp/kcov
  #- [ "$TRAVIS_OS_NAME" != "osx" ] && mkdir ${TRAVIS_BUILD_DIR}/kcov
  #- [ "$TRAVIS_OS_NAME" != "osx" ] && wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz && tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build && cmake .. && make && make install DESTDIR=../tmp && popd
  #- [ "$TRAVIS_OS_NAME" != "osx" ] && export KCOV="/tmp/kcov/kcov-master/tmp/usr/local/bin/kcov --coveralls-id=$TRAVIS_JOB_ID ${TRAVIS_BUILD_DIR}/kcov"
  - export NOOK=1
  - export NOREPORT=1
  - cd radare2-regressions
  - cd new
  - npm install
  - node bin/r2r.js
  - cd ..
  - VERBOSE=1 make -k all
  - make unit_tests

notifications:
  irc: "chat.freenode.net#radare"
  on_success: never
  on_failure: always
