name: CentOS 6 test

on:
  push:
    branches:
    - 'pre-release*'
    - 'prerelease*'
    - 'release-*'
    - 'centos*'
  schedule:
    - cron: '0 18 * * 1,3,5' # Three-weekly at 18:00 UTC on Monday, Wednesday, and Friday

jobs:
  build:
    name: centos-6-build
    runs-on: ubuntu-latest
    container: centos:6

    steps:
    - name: Install tools
      run: yum install -y patch unzip git gcc make
    - name: Checkout r2
      run: |
        git clone https://github.com/${{ github.repository }}
        cd radare2
        git fetch origin ${{ github.ref }}
        git checkout -b local_branch FETCH_HEAD
    - name: Configure with ACR and build
      run: ./configure --prefix=/usr && make CS_RELEASE=1
      working-directory: radare2
    - name: Install with make
      run: make install
      working-directory: radare2
    - name: Run tests
      run: cd test/unit && make && make fuzz-tests
      working-directory: radare2
      env:
        # `make install` installs, for some unknown reasons, pkgconfig files in
        # /usr/lib and not in /usr/lib64, thus pkg-config cannot find the right
        # .pc files if the right path is not specified
        PKG_CONFIG_PATH: /usr/lib/pkgconfig
