name: Debian OLD

on:
  push:
    branches:
    - 'pre-release*'
    - 'prerelease*'
    - 'release-*'
    - 'debian*'
  schedule:
    - cron: '0 18 * * 1,3,5' # Three-weekly at 18:00 UTC on Monday, Wednesday, and Friday

jobs:
  build:
    name: debian-oldies-build
    strategy:
        matrix:
            container:
                - debian:wheezy
                - debian:jessie

    runs-on: ubuntu-latest
    container: ${{ matrix.container }}

    steps:
    - name: Fix containers (Wheezy)
      if: matrix.container == 'debian:wheezy'
      run: |
          sed -i '/deb http:\/\/deb.debian.org\/debian wheezy-updates main/d' /etc/apt/sources.list
          echo "deb http://archive.debian.org/debian wheezy main" > /etc/apt/sources.list
          echo "deb http://archive.debian.org/debian-security wheezy/updates main" >> /etc/apt/sources.list
          echo "Acquire::Check-Valid-Until no;" > /etc/apt/apt.conf.d/99no-check-valid-until

    - name: Install tools
      run: apt-get update && apt-get install --yes patch unzip git gcc make curl pkg-config libc6-i386 build-essential
    - name: Install Python source build dependcies
      run: apt-get install --yes checkinstall libbz2-dev libc6-dev libgdbm-dev libncursesw5-dev libreadline-gplv2-dev libssl-dev libsqlite3-dev tk-dev
    - name: Install Python from source
      run: |
        curl -o Python-3.6.9.tgz https://www.python.org/ftp/python/3.6.9/Python-3.6.9.tgz
        tar -zxvf Python-3.6.9.tgz
        cd Python-3.6.9/
        ./configure
        make install
    - name: Checkout r2
      run: |
        git clone https://github.com/${{ github.repository }}
        cd radare2
        git fetch origin ${{ github.ref }}
        git checkout -b local_branch FETCH_HEAD
    - name: Checkout our Testsuite Binaries
      run: git clone https://github.com/radareorg/radare2-testbins test/bins
    - name: Configure with ACR and build
      run: ./configure --prefix=/usr && make
      working-directory: radare2
    - name: Install with make
      run: make install
      working-directory: radare2
    - name: Install test dependencies
      run: python3 -m pip install --user 'git+https://github.com/radareorg/radare2-r2pipe#egg=r2pipe&subdirectory=python'
    - name: Run tests
      run: cd test && make
      working-directory: radare2
      env:
        PKG_CONFIG_PATH: /usr/lib/x86_64-linux-gnu/pkgconfig
