name: freebsd

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  freebsd:
    runs-on: macos-10.15
    name: freebsd-acr
    steps:
    - uses: actions/checkout@v2
    - name: Build r2 in FreeBSD
      id: build
      uses: vmactions/freebsd-vm@v0.1.6
      with:
        usesh: true
        prepare: pkg install -y curl gmake patch git
        run: |
          cd work || true
          pwd
          ls -lah
          whoami
          env
          freebsd-version
          echo DATE: ; date
          sys/install.sh
          gmake install DESTDIR=/tmp/prefix
          (cd /tmp/prefix ; tar czvf /tmp/radare2-freebsd.tgz *)
          r2r test/db/cmd
          rm -rf *
          cp /tmp/radare2-freebsd.tgz .
          echo DATE: ; date
    - uses: actions/upload-artifact@v2
      with:
        path: radare2-freebsd.tgz
